// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcOkHCmJgo2INXBaIa5X8_Y2evXyHZ2M',
    appId: '1:587596223692:web:f807cd7896819f444cde69',
    messagingSenderId: '587596223692',
    projectId: 'stratvault',
    authDomain: 'stratvault.firebaseapp.com',
    storageBucket: 'stratvault.firebasestorage.app',
    measurementId: 'G-KX05XCTCPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbs3MfU_XQ0lo3IufQbWggyz4sAV1YWWE',
    appId: '1:587596223692:android:010f98530ff0f41f4cde69',
    messagingSenderId: '587596223692',
    projectId: 'stratvault',
    storageBucket: 'stratvault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvqEWaSc4dPNi_MZlY9joWfMVdypXJeAo',
    appId: '1:587596223692:ios:4abfe149e6feec334cde69',
    messagingSenderId: '587596223692',
    projectId: 'stratvault',
    storageBucket: 'stratvault.firebasestorage.app',
    iosBundleId: 'com.example.stratVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvqEWaSc4dPNi_MZlY9joWfMVdypXJeAo',
    appId: '1:587596223692:ios:4abfe149e6feec334cde69',
    messagingSenderId: '587596223692',
    projectId: 'stratvault',
    storageBucket: 'stratvault.firebasestorage.app',
    iosBundleId: 'com.example.stratVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALcOkHCmJgo2INXBaIa5X8_Y2evXyHZ2M',
    appId: '1:587596223692:web:4bf1558a8a89e16c4cde69',
    messagingSenderId: '587596223692',
    projectId: 'stratvault',
    authDomain: 'stratvault.firebaseapp.com',
    storageBucket: 'stratvault.firebasestorage.app',
    measurementId: 'G-E2SE1C82RE',
  );

}